// checkCollisions : Pacman [List-of Ghost] Configuration -> void
// checks if pacman collided with any ghosts, dots, or power pellets
function checkCollisions(pacman, listOfGhosts, gc) {
    // ghost collisions
    for (var i = 0; i < listOfGhosts.length; i++) {
        // if collision (same position and ghost is not resetting)
        if (posnEqual(pacman.position, listOfGhosts[i].position) && !listOfGhosts[i].eaten) {
            //console.log("collision");
            // pacman eats ghost -> send ghost back to start
            if (listOfGhosts[i].frightened > 0) {
                listOfGhosts[i].eaten = true;
                game.score += 20;
            } else { // ghost eats pacman
                pacman.dying = 15;
            }
        }
    }
    // dot collisions
    for (var i = 0; i < gc.dots.length; i++) {
        if (posnEqual(pacman.position, gc.dots[i])) {
            gc.dots.splice(i, 1);
            game.score += 1;
        }
    }
    // power pellet collisions
    for (var i = 0; i < gc.powers.length; i++) {
        if (posnEqual(pacman.position, gc.powers[i])) {
            gc.powers.splice(i, 1);
            game.score += 5;
            // scare ghosts
            for (var i = 0; i < listOfGhosts.length; i++) {
                if (!listOfGhosts[i].eaten) {
                    listOfGhosts[i].frightened = 10;
                }
            }
        }
    }
}

// swappingWithAny : Pacman [List-of Ghost] -> Boolean
// is pacman swapping positions with any ghost?
function swappingWithAny(pacman, listOfGhosts) {
    for (var i = 0; i < listOfGhosts.length; i++) {
        if (swappingPositions(pacman.position, pacman.direction, listOfGhosts[i].position, listOfGhosts[i].direction)) {
            return true;
        }
    }
    return false;
}

// swappingPositions : Posn Dir Posn Dir -> Boolean
// are the pacman and ghost swapping positions (facing each other)?
function swappingPositions(pacPosition, pacDirection, ghoPosition, ghoDirection) {
    var newGhoPosition;
    switch (pacDirection) {
        case "left": // check if ghost is to the left of pacman -> move ghost to the right
            newGhoPosition = new Posn(ghoPosition.x + 1, ghoPosition.y);
            break;
        case "right": // check if ghost is to the right of pacman -> move ghost to the left
            newGhoPosition = new Posn(ghoPosition.x - 1, ghoPosition.y);
            break;
        case "up": // check if ghost is above pacman -> move ghost down
            newGhoPosition = new Posn(ghoPosition.x, ghoPosition.y + 1);
            break;
        case "down": // check if ghost is below pacman -> most ghost up
            newGhoPosition = new Posn(ghoPosition.x, ghoPosition.y - 1);
            break;
        default:
            return false;
    }
    return pacDirection === reverseDirection(ghoDirection) && posnEqual(pacPosition, newGhoPosition);
}

// drawBoard : [List-of Cell] Number Number -> void
// draws the baord
function drawBoard(listofCells, width, height) {
    //BACKGROUND
    fill(0);
    rect(width / 2.0 * CELLSIZE, height / 2.0 * CELLSIZE, width * CELLSIZE, height * CELLSIZE);
    //CELLS
    for (var i = 0; i < listofCells.length; i++) {
        listofCells[i].draw();
    }

}

// drawGhosts : [List-of Ghost] -> void
// draws the ghosts
function drawGhosts(listOfGhosts) {
    for (var i = 0; i < listOfGhosts.length; i++) {
        listOfGhosts[i].draw();
    }
}

// updateGhosts : [List-of Ghost] Pacman Configuration -> void
// updates the ghosts' position
function updateGhosts(listOfGhosts, pacman, gc) {
    for (var i = 0; i < listOfGhosts.length; i++) {
        listOfGhosts[i].update(pacman, gc);
    }
}

// getCell : Posn [List-of Cell] -> Cell
// finds the cell with the given position
function getCell(posn, board) {
    var cell = new Cell(new Posn(-1, -1), []);
    for (var i = 0; i < board.length; i++) {
        if (posnEqual(board[i].position, posn)) {
            cell = board[i];
            break;
        }
    }
    return cell;
}

// posnEqual : Posn Posn -> Boolean
// are two posns equal?
function posnEqual(posn1, posn2) {
    return ((posn1.x === posn2.x) && (posn1.y === posn2.y));
}

// reverseDirection : Dir -> Dir
// returns the opposite direction
function reverseDirection(direction) {
    switch (direction) {
        case "left":
            return "right";
        case "right":
            return "left";
        case "up":
            return "down";
        case "down":
            return "up";
        default:
            return "";
    }
}

// gridToCenterPx : Number -> Number
// converts the grid position into its bitmap position (center of the grid)
function gridToCenterPx(grid) {
    var x = grid.x * CELLSIZE + 10;
    var y = grid.y * CELLSIZE + 10;
    return new Posn(x, y);
}

// createGame : void -> PacmanGame
// creates the initial game
function createGame() {
    var gc = createConfiguration();
    return new PacmanGame(new Pacman(true, "", gc.start, 3),
        [new Ghost("blinky", "", new Posn(12, 13), 0, true, 0),
        new Ghost("clyde", "", new Posn(13, 14), 0, true, 0),
        new Ghost("inky", "", new Posn(12, 14), 0, true, 0),
        new Ghost("pinky", "", new Posn(13, 13), 0, true, 0)
        ],
        gc);
}

// createConfiguration: void -> Configuration
// creates the game configuration
function createConfiguration() {
    var width = 26; // 26 cells wide
    var height = 29; // 29 cells tall
    var board = initializeBoard();
    var start = new Posn(12, 22); // pacman starts at (12, 22)
    var dots = initializeDots(); // regular dots
    var powers = [new Posn(0, 2), new Posn(0, 22), new Posn(25, 2), new Posn(25, 22)]; // power pellets
    var ghostStarts = [new Posn(5, 4), new Posn(20, 4), new Posn(5, 20), new Posn(20, 20)]; // ghost starting positions
    return new Configuration(width, height, board, start, dots, powers, ghostStarts);
}

// initializeDots : void -> [List-of Posn]
// creates all the dots
function initializeDots() {
    return [new Posn(0, 0), new Posn(0, 1), new Posn(0, 3), new Posn(0, 4), new Posn(0, 5), new Posn(0, 6),
    new Posn(0, 7), new Posn(0, 19), new Posn(0, 20), new Posn(0, 21), new Posn(0, 25), new Posn(0, 26),
    new Posn(0, 27), new Posn(0, 28), new Posn(1, 0), new Posn(1, 4), new Posn(1, 7), new Posn(1, 19),
    new Posn(1, 22), new Posn(1, 25), new Posn(1, 28), new Posn(2, 0), new Posn(2, 4), new Posn(2, 7),
    new Posn(2, 19), new Posn(2, 22), new Posn(2, 23), new Posn(2, 24), new Posn(2, 25), new Posn(2, 28),
    new Posn(3, 0), new Posn(3, 4), new Posn(3, 7), new Posn(3, 19), new Posn(3, 25), new Posn(3, 28),
    new Posn(4, 0), new Posn(4, 4), new Posn(4, 7), new Posn(4, 19), new Posn(4, 25), new Posn(4, 28),
    new Posn(5, 0), new Posn(5, 1), new Posn(5, 2), new Posn(5, 3), new Posn(5, 4), new Posn(5, 5),
    new Posn(5, 6), new Posn(5, 7), new Posn(5, 8), new Posn(5, 9), new Posn(5, 10), new Posn(5, 11),
    new Posn(5, 12), new Posn(5, 13), new Posn(5, 14), new Posn(5, 15), new Posn(5, 16), new Posn(5, 17),
    new Posn(5, 18), new Posn(5, 19), new Posn(5, 20), new Posn(5, 21), new Posn(5, 22), new Posn(5, 23),
    new Posn(5, 24), new Posn(5, 25), new Posn(5, 28), new Posn(6, 0), new Posn(6, 4), new Posn(6, 19),
    new Posn(6, 22), new Posn(6, 28), new Posn(7, 0), new Posn(7, 4), new Posn(7, 19), new Posn(7, 22),
    new Posn(7, 28), new Posn(8, 0), new Posn(8, 4), new Posn(8, 5), new Posn(8, 6), new Posn(8, 7),
    new Posn(8, 19), new Posn(8, 22), new Posn(8, 23), new Posn(8, 24), new Posn(8, 25), new Posn(8, 28),
    new Posn(9, 0), new Posn(9, 4), new Posn(9, 7), new Posn(9, 19), new Posn(9, 22), new Posn(9, 25),
    new Posn(9, 28), new Posn(10, 0), new Posn(10, 4), new Posn(10, 7), new Posn(10, 19), new Posn(10, 22),
    new Posn(10, 25), new Posn(10, 28), new Posn(11, 0), new Posn(11, 1), new Posn(11, 2), new Posn(11, 3),
    new Posn(11, 4), new Posn(11, 7), new Posn(11, 19), new Posn(11, 20), new Posn(11, 21), new Posn(11, 22),
    new Posn(11, 25), new Posn(11, 26), new Posn(11, 27), new Posn(11, 28), new Posn(12, 4),
    new Posn(12, 28), new Posn(13, 4), new Posn(13, 22), new Posn(13, 28), new Posn(14, 0), new Posn(14, 1),
    new Posn(14, 1), new Posn(14, 2), new Posn(14, 3), new Posn(14, 4), new Posn(14, 7), new Posn(14, 19),
    new Posn(14, 20), new Posn(14, 21), new Posn(14, 22), new Posn(14, 25), new Posn(14, 26), new Posn(14, 27),
    new Posn(14, 28), new Posn(15, 0), new Posn(15, 4), new Posn(15, 7), new Posn(15, 19), new Posn(15, 22),
    new Posn(15, 25), new Posn(15, 28), new Posn(16, 0), new Posn(16, 4), new Posn(16, 7), new Posn(16, 19),
    new Posn(16, 22), new Posn(16, 25), new Posn(16, 28), new Posn(17, 0), new Posn(17, 4), new Posn(17, 5),
    new Posn(17, 6), new Posn(17, 7), new Posn(17, 19), new Posn(17, 22), new Posn(17, 23), new Posn(17, 24),
    new Posn(17, 25), new Posn(17, 28), new Posn(18, 0), new Posn(18, 4), new Posn(18, 19), new Posn(18, 22),
    new Posn(18, 28), new Posn(19, 0), new Posn(19, 4), new Posn(19, 19), new Posn(19, 22), new Posn(19, 28),
    new Posn(20, 0), new Posn(20, 1), new Posn(20, 2), new Posn(20, 3), new Posn(20, 4), new Posn(20, 5),
    new Posn(20, 6), new Posn(20, 7), new Posn(20, 8), new Posn(20, 9), new Posn(20, 10), new Posn(20, 11),
    new Posn(20, 12), new Posn(20, 13), new Posn(20, 14), new Posn(20, 15), new Posn(20, 16), new Posn(20, 17),
    new Posn(20, 18), new Posn(20, 19), new Posn(20, 20), new Posn(20, 21), new Posn(20, 22), new Posn(20, 23),
    new Posn(20, 24), new Posn(20, 25), new Posn(20, 28), new Posn(21, 0), new Posn(21, 4), new Posn(21, 7),
    new Posn(21, 19), new Posn(21, 25), new Posn(21, 28), new Posn(22, 0), new Posn(22, 4), new Posn(22, 7),
    new Posn(22, 19), new Posn(22, 25), new Posn(22, 28), new Posn(23, 0), new Posn(23, 4), new Posn(23, 7),
    new Posn(23, 19), new Posn(23, 22), new Posn(23, 23), new Posn(23, 24), new Posn(23, 25), new Posn(23, 28), new Posn(24, 0),
    new Posn(24, 4), new Posn(24, 7), new Posn(24, 19), new Posn(24, 22), new Posn(24, 25), new Posn(24, 28),
    new Posn(25, 0), new Posn(25, 1), new Posn(25, 3), new Posn(25, 4), new Posn(25, 5), new Posn(25, 6),
    new Posn(25, 7), new Posn(25, 19), new Posn(25, 20), new Posn(25, 21), new Posn(25, 25), new Posn(25, 26),
    new Posn(25, 27), new Posn(25, 28)
    ];
}

// initializeBoard : void -> [List-of Cell]
// creates all the cells in the board
function initializeBoard() {
    return [new Cell(new Posn(0, 0), ["up", "left"]),
    new Cell(new Posn(1, 0), ["up", "down"]),
    new Cell(new Posn(2, 0), ["up", "down"]),
    new Cell(new Posn(3, 0), ["up", "down"]),
    new Cell(new Posn(4, 0), ["up", "down"]),
    new Cell(new Posn(5, 0), ["up"]),
    new Cell(new Posn(6, 0), ["up", "down"]),
    new Cell(new Posn(7, 0), ["up", "down"]),
    new Cell(new Posn(8, 0), ["up", "down"]),
    new Cell(new Posn(9, 0), ["up", "down"]),
    new Cell(new Posn(10, 0), ["up", "down"]),
    new Cell(new Posn(11, 0), ["up", "right"]),
    new Cell(new Posn(12, 0), ["up", "left"]),
    new Cell(new Posn(13, 0), ["up", "right"]),
    new Cell(new Posn(14, 0), ["up", "left"]),
    new Cell(new Posn(15, 0), ["up", "down"]),
    new Cell(new Posn(16, 0), ["up", "down"]),
    new Cell(new Posn(17, 0), ["up", "down"]),
    new Cell(new Posn(18, 0), ["up", "down"]),
    new Cell(new Posn(19, 0), ["up", "down"]),
    new Cell(new Posn(20, 0), ["up"]),
    new Cell(new Posn(21, 0), ["up", "down"]),
    new Cell(new Posn(22, 0), ["up", "down"]),
    new Cell(new Posn(23, 0), ["up", "down"]),
    new Cell(new Posn(24, 0), ["up", "down"]),
    new Cell(new Posn(25, 0), ["up", "right"]),
    new Cell(new Posn(0, 1), ["left", "right"]),
    new Cell(new Posn(1, 1), ["up", "left"]),
    new Cell(new Posn(2, 1), ["up"]),
    new Cell(new Posn(3, 1), ["up"]),
    new Cell(new Posn(4, 1), ["up", "right"]),
    new Cell(new Posn(5, 1), ["left", "right"]),
    new Cell(new Posn(6, 1), ["up", "left"]),
    new Cell(new Posn(7, 1), ["up"]),
    new Cell(new Posn(8, 1), ["up"]),
    new Cell(new Posn(9, 1), ["up"]),
    new Cell(new Posn(10, 1), ["up", "right"]),
    new Cell(new Posn(11, 1), ["left", "right"]),
    new Cell(new Posn(12, 1), ["left"]),
    new Cell(new Posn(13, 1), ["right"]),
    new Cell(new Posn(14, 1), ["left", "right"]),
    new Cell(new Posn(15, 1), ["up", "left"]),
    new Cell(new Posn(16, 1), ["up"]),
    new Cell(new Posn(17, 1), ["up"]),
    new Cell(new Posn(18, 1), ["up"]),
    new Cell(new Posn(19, 1), ["up", "right"]),
    new Cell(new Posn(20, 1), ["left", "right"]),
    new Cell(new Posn(21, 1), ["up", "left"]),
    new Cell(new Posn(22, 1), ["up"]),
    new Cell(new Posn(23, 1), ["up"]),
    new Cell(new Posn(24, 1), ["up", "right"]),
    new Cell(new Posn(25, 1), ["left", "right"]),
    new Cell(new Posn(0, 2), ["left", "right"]),
    new Cell(new Posn(1, 2), ["left"]),
    new Cell(new Posn(2, 2), []),
    new Cell(new Posn(3, 2), []),
    new Cell(new Posn(4, 2), ["right"]),
    new Cell(new Posn(5, 2), ["left", "right"]),
    new Cell(new Posn(6, 2), ["left"]),
    new Cell(new Posn(7, 2), []),
    new Cell(new Posn(8, 2), []),
    new Cell(new Posn(9, 2), []),
    new Cell(new Posn(10, 2), ["right"]),
    new Cell(new Posn(11, 2), ["left", "right"]),
    new Cell(new Posn(12, 2), ["left"]),
    new Cell(new Posn(13, 2), ["right"]),
    new Cell(new Posn(14, 2), ["left", "right"]),
    new Cell(new Posn(15, 2), ["left"]),
    new Cell(new Posn(16, 2), []),
    new Cell(new Posn(17, 2), []),
    new Cell(new Posn(18, 2), []),
    new Cell(new Posn(19, 2), ["right"]),
    new Cell(new Posn(20, 2), ["left", "right"]),
    new Cell(new Posn(21, 2), ["left"]),
    new Cell(new Posn(22, 2), []),
    new Cell(new Posn(23, 2), []),
    new Cell(new Posn(24, 2), ["right"]),
    new Cell(new Posn(25, 2), ["left", "right"]),
    new Cell(new Posn(0, 3), ["left", "right"]),
    new Cell(new Posn(1, 3), ["left", "down"]),
    new Cell(new Posn(2, 3), ["down"]),
    new Cell(new Posn(3, 3), ["down"]),
    new Cell(new Posn(4, 3), ["right", "down"]),
    new Cell(new Posn(5, 3), ["left", "right"]),
    new Cell(new Posn(6, 3), ["left", "down"]),
    new Cell(new Posn(7, 3), ["down"]),
    new Cell(new Posn(8, 3), ["down"]),
    new Cell(new Posn(9, 3), ["down"]),
    new Cell(new Posn(10, 3), ["right", "down"]),
    new Cell(new Posn(11, 3), ["left", "right"]),
    new Cell(new Posn(12, 3), ["left", "down"]),
    new Cell(new Posn(13, 3), ["right", "down"]),
    new Cell(new Posn(14, 3), ["left", "right"]),
    new Cell(new Posn(15, 3), ["left", "down"]),
    new Cell(new Posn(16, 3), ["down"]),
    new Cell(new Posn(17, 3), ["down"]),
    new Cell(new Posn(18, 3), ["down"]),
    new Cell(new Posn(19, 3), ["right", "down"]),
    new Cell(new Posn(20, 3), ["left", "right"]),
    new Cell(new Posn(21, 3), ["left", "down"]),
    new Cell(new Posn(22, 3), ["down"]),
    new Cell(new Posn(23, 3), ["down"]),
    new Cell(new Posn(24, 3), ["right", "down"]),
    new Cell(new Posn(25, 3), ["left", "right"]),
    new Cell(new Posn(0, 4), ["left"]),
    new Cell(new Posn(1, 4), ["up", "down"]),
    new Cell(new Posn(2, 4), ["up", "down"]),
    new Cell(new Posn(3, 4), ["up", "down"]),
    new Cell(new Posn(4, 4), ["up", "down"]),
    new Cell(new Posn(5, 4), []),
    new Cell(new Posn(6, 4), ["up", "down"]),
    new Cell(new Posn(7, 4), ["up", "down"]),
    new Cell(new Posn(8, 4), ["up"]),
    new Cell(new Posn(9, 4), ["up", "down"]),
    new Cell(new Posn(10, 4), ["up", "down"]),
    new Cell(new Posn(11, 4), ["down"]),
    new Cell(new Posn(12, 4), ["up", "down"]),
    new Cell(new Posn(13, 4), ["up", "down"]),
    new Cell(new Posn(14, 4), ["down"]),
    new Cell(new Posn(15, 4), ["up", "down"]),
    new Cell(new Posn(16, 4), ["up", "down"]),
    new Cell(new Posn(17, 4), ["up"]),
    new Cell(new Posn(18, 4), ["up", "down"]),
    new Cell(new Posn(19, 4), ["up", "down"]),
    new Cell(new Posn(20, 4), []),
    new Cell(new Posn(21, 4), ["up", "down"]),
    new Cell(new Posn(22, 4), ["up", "down"]),
    new Cell(new Posn(23, 4), ["up", "down"]),
    new Cell(new Posn(24, 4), ["up", "down"]),
    new Cell(new Posn(25, 4), ["right"]),
    new Cell(new Posn(0, 5), ["left", "right"]),
    new Cell(new Posn(1, 5), ["up", "left"]),
    new Cell(new Posn(2, 5), ["up"]),
    new Cell(new Posn(3, 5), ["up"]),
    new Cell(new Posn(4, 5), ["up", "right"]),
    new Cell(new Posn(5, 5), ["left", "right"]),
    new Cell(new Posn(6, 5), ["up", "left"]),
    new Cell(new Posn(7, 5), ["up", "right"]),
    new Cell(new Posn(8, 5), ["left", "right"]),
    new Cell(new Posn(9, 5), ["up", "left"]),
    new Cell(new Posn(10, 5), ["up"]),
    new Cell(new Posn(11, 5), ["up"]),
    new Cell(new Posn(12, 5), ["up"]),
    new Cell(new Posn(13, 5), ["up"]),
    new Cell(new Posn(14, 5), ["up"]),
    new Cell(new Posn(15, 5), ["up"]),
    new Cell(new Posn(16, 5), ["up", "right"]),
    new Cell(new Posn(17, 5), ["left", "right"]),
    new Cell(new Posn(18, 5), ["up", "left"]),
    new Cell(new Posn(19, 5), ["up", "right"]),
    new Cell(new Posn(20, 5), ["left", "right"]),
    new Cell(new Posn(21, 5), ["up", "left"]),
    new Cell(new Posn(22, 5), ["up"]),
    new Cell(new Posn(23, 5), ["up"]),
    new Cell(new Posn(24, 5), ["up", "right"]),
    new Cell(new Posn(25, 5), ["left", "right"]),
    new Cell(new Posn(0, 6), ["left", "right"]),
    new Cell(new Posn(1, 6), ["left", "down"]),
    new Cell(new Posn(2, 6), ["down"]),
    new Cell(new Posn(3, 6), ["down"]),
    new Cell(new Posn(4, 6), ["right", "down"]),
    new Cell(new Posn(5, 6), ["left", "right"]),
    new Cell(new Posn(6, 6), ["left"]),
    new Cell(new Posn(7, 6), ["right"]),
    new Cell(new Posn(8, 6), ["left", "right"]),
    new Cell(new Posn(9, 6), ["left", "down"]),
    new Cell(new Posn(10, 6), ["down"]),
    new Cell(new Posn(11, 6), ["down"]),
    new Cell(new Posn(12, 6), []),
    new Cell(new Posn(13, 6), []),
    new Cell(new Posn(14, 6), ["down"]),
    new Cell(new Posn(15, 6), ["down"]),
    new Cell(new Posn(16, 6), ["right", "down"]),
    new Cell(new Posn(17, 6), ["left", "right"]),
    new Cell(new Posn(18, 6), ["left"]),
    new Cell(new Posn(19, 6), ["right"]),
    new Cell(new Posn(20, 6), ["left", "right"]),
    new Cell(new Posn(21, 6), ["left", "down"]),
    new Cell(new Posn(22, 6), ["down"]),
    new Cell(new Posn(23, 6), ["down"]),
    new Cell(new Posn(24, 6), ["right", "down"]),
    new Cell(new Posn(25, 6), ["left", "right"]),
    new Cell(new Posn(0, 7), ["left", "down"]),
    new Cell(new Posn(1, 7), ["up", "down"]),
    new Cell(new Posn(2, 7), ["up", "down"]),
    new Cell(new Posn(3, 7), ["up", "down"]),
    new Cell(new Posn(4, 7), ["up", "down"]),
    new Cell(new Posn(5, 7), ["right"]),
    new Cell(new Posn(6, 7), ["left"]),
    new Cell(new Posn(7, 7), ["right"]),
    new Cell(new Posn(8, 7), ["left", "down"]),
    new Cell(new Posn(9, 7), ["up", "down"]),
    new Cell(new Posn(10, 7), ["up", "down"]),
    new Cell(new Posn(11, 7), ["up", "right"]),
    new Cell(new Posn(12, 7), ["left"]),
    new Cell(new Posn(13, 7), ["right"]),
    new Cell(new Posn(14, 7), ["up", "left"]),
    new Cell(new Posn(15, 7), ["up", "down"]),
    new Cell(new Posn(16, 7), ["up", "down"]),
    new Cell(new Posn(17, 7), ["right", "down"]),
    new Cell(new Posn(18, 7), ["left"]),
    new Cell(new Posn(19, 7), ["right"]),
    new Cell(new Posn(20, 7), ["left"]),
    new Cell(new Posn(21, 7), ["up", "down"]),
    new Cell(new Posn(22, 7), ["up", "down"]),
    new Cell(new Posn(23, 7), ["up", "down"]),
    new Cell(new Posn(24, 7), ["up", "down"]),
    new Cell(new Posn(25, 7), ["right", "down"]),
    new Cell(new Posn(0, 8), ["up", "left"]),
    new Cell(new Posn(1, 8), ["up"]),
    new Cell(new Posn(2, 8), ["up"]),
    new Cell(new Posn(3, 8), ["up"]),
    new Cell(new Posn(4, 8), ["up", "right"]),
    new Cell(new Posn(5, 8), ["left", "right"]),
    new Cell(new Posn(6, 8), ["left"]),
    new Cell(new Posn(7, 8), []),
    new Cell(new Posn(8, 8), ["up"]),
    new Cell(new Posn(9, 8), ["up"]),
    new Cell(new Posn(10, 8), ["up", "right"]),
    new Cell(new Posn(11, 8), ["left", "right"]),
    new Cell(new Posn(12, 8), ["left"]),
    new Cell(new Posn(13, 8), ["right"]),
    new Cell(new Posn(14, 8), ["left", "right"]),
    new Cell(new Posn(15, 8), ["up", "left"]),
    new Cell(new Posn(16, 8), ["up"]),
    new Cell(new Posn(17, 8), ["up"]),
    new Cell(new Posn(18, 8), []),
    new Cell(new Posn(19, 8), ["right"]),
    new Cell(new Posn(20, 8), ["left", "right"]),
    new Cell(new Posn(21, 8), ["up", "left"]),
    new Cell(new Posn(22, 8), ["up"]),
    new Cell(new Posn(23, 8), ["up"]),
    new Cell(new Posn(24, 8), ["up"]),
    new Cell(new Posn(25, 8), ["up", "right"]),
    new Cell(new Posn(0, 9), ["left"]),
    new Cell(new Posn(1, 9), []),
    new Cell(new Posn(2, 9), []),
    new Cell(new Posn(3, 9), []),
    new Cell(new Posn(4, 9), ["right"]),
    new Cell(new Posn(5, 9), ["left", "right"]),
    new Cell(new Posn(6, 9), ["left"]),
    new Cell(new Posn(7, 9), []),
    new Cell(new Posn(8, 9), ["down"]),
    new Cell(new Posn(9, 9), ["down"]),
    new Cell(new Posn(10, 9), ["right", "down"]),
    new Cell(new Posn(11, 9), ["left", "right"]),
    new Cell(new Posn(12, 9), ["left", "down"]),
    new Cell(new Posn(13, 9), ["right", "down"]),
    new Cell(new Posn(14, 9), ["left", "right"]),
    new Cell(new Posn(15, 9), ["left", "down"]),
    new Cell(new Posn(16, 9), ["down"]),
    new Cell(new Posn(17, 9), ["down"]),
    new Cell(new Posn(18, 9), []),
    new Cell(new Posn(19, 9), ["right"]),
    new Cell(new Posn(20, 9), ["left", "right"]),
    new Cell(new Posn(21, 9), ["left"]),
    new Cell(new Posn(22, 9), []),
    new Cell(new Posn(23, 9), []),
    new Cell(new Posn(24, 9), []),
    new Cell(new Posn(25, 9), ["right"]),
    new Cell(new Posn(0, 10), ["left"]),
    new Cell(new Posn(1, 10), []),
    new Cell(new Posn(2, 10), []),
    new Cell(new Posn(3, 10), []),
    new Cell(new Posn(4, 10), ["right"]),
    new Cell(new Posn(5, 10), ["left", "right"]),
    new Cell(new Posn(6, 10), ["left"]),
    new Cell(new Posn(7, 10), ["right"]),
    new Cell(new Posn(8, 10), ["up", "left"]),
    new Cell(new Posn(9, 10), ["up"]),
    new Cell(new Posn(10, 10), ["up"]),
    new Cell(new Posn(11, 10), []),
    new Cell(new Posn(12, 10), ["up"]),
    new Cell(new Posn(13, 10), ["up"]),
    new Cell(new Posn(14, 10), []),
    new Cell(new Posn(15, 10), ["up"]),
    new Cell(new Posn(16, 10), ["up"]),
    new Cell(new Posn(17, 10), ["up", "right"]),
    new Cell(new Posn(18, 10), ["left"]),
    new Cell(new Posn(19, 10), ["right"]),
    new Cell(new Posn(20, 10), ["left", "right"]),
    new Cell(new Posn(21, 10), ["left"]),
    new Cell(new Posn(22, 10), []),
    new Cell(new Posn(23, 10), []),
    new Cell(new Posn(24, 10), []),
    new Cell(new Posn(25, 10), ["right"]),
    new Cell(new Posn(0, 11), ["left"]),
    new Cell(new Posn(1, 11), []),
    new Cell(new Posn(2, 11), []),
    new Cell(new Posn(3, 11), []),
    new Cell(new Posn(4, 11), ["right"]),
    new Cell(new Posn(5, 11), ["left", "right"]),
    new Cell(new Posn(6, 11), ["left"]),
    new Cell(new Posn(7, 11), ["right"]),
    new Cell(new Posn(8, 11), ["left"]),
    new Cell(new Posn(9, 11), ["down"]),
    new Cell(new Posn(10, 11), ["down"]),
    new Cell(new Posn(11, 11), ["down"]),
    new Cell(new Posn(12, 11), ["down"]),
    new Cell(new Posn(13, 11), ["down"]),
    new Cell(new Posn(14, 11), ["down"]),
    new Cell(new Posn(15, 11), ["down"]),
    new Cell(new Posn(16, 11), ["down"]),
    new Cell(new Posn(17, 11), ["right"]),
    new Cell(new Posn(18, 11), ["left"]),
    new Cell(new Posn(19, 11), ["right"]),
    new Cell(new Posn(20, 11), ["left", "right"]),
    new Cell(new Posn(21, 11), ["left"]),
    new Cell(new Posn(22, 11), []),
    new Cell(new Posn(23, 11), []),
    new Cell(new Posn(24, 11), []),
    new Cell(new Posn(25, 11), ["right"]),
    new Cell(new Posn(0, 12), ["left", "down"]),
    new Cell(new Posn(1, 12), ["down"]),
    new Cell(new Posn(2, 12), ["down"]),
    new Cell(new Posn(3, 12), ["down"]),
    new Cell(new Posn(4, 12), ["right", "down"]),
    new Cell(new Posn(5, 12), ["left", "right"]),
    new Cell(new Posn(6, 12), ["left", "down"]),
    new Cell(new Posn(7, 12), ["right", "down"]),
    new Cell(new Posn(8, 12), ["left", "right"]),
    new Cell(new Posn(9, 12), ["up", "left"]),
    new Cell(new Posn(10, 12), ["up"]),
    new Cell(new Posn(11, 12), ["up"]),
    new Cell(new Posn(12, 12), ["special"]),
    new Cell(new Posn(13, 12), ["special"]),
    new Cell(new Posn(14, 12), ["up"]),
    new Cell(new Posn(15, 12), ["up"]),
    new Cell(new Posn(16, 12), ["up", "right"]),
    new Cell(new Posn(17, 12), ["left", "right"]),
    new Cell(new Posn(18, 12), ["left", "down"]),
    new Cell(new Posn(19, 12), ["right", "down"]),
    new Cell(new Posn(20, 12), ["left", "right"]),
    new Cell(new Posn(21, 12), ["left", "down"]),
    new Cell(new Posn(22, 12), ["down"]),
    new Cell(new Posn(23, 12), ["down"]),
    new Cell(new Posn(24, 12), ["down"]),
    new Cell(new Posn(25, 12), ["right", "down"]),
    new Cell(new Posn(0, 13), ["up", "down"]),
    new Cell(new Posn(1, 13), ["up", "down"]),
    new Cell(new Posn(2, 13), ["up", "down"]),
    new Cell(new Posn(3, 13), ["up", "down"]),
    new Cell(new Posn(4, 13), ["up", "down"]),
    new Cell(new Posn(5, 13), []),
    new Cell(new Posn(6, 13), ["up", "down"]),
    new Cell(new Posn(7, 13), ["up", "down"]),
    new Cell(new Posn(8, 13), ["right"]),
    new Cell(new Posn(9, 13), ["left"]),
    new Cell(new Posn(10, 13), []),
    new Cell(new Posn(11, 13), []),
    new Cell(new Posn(12, 13), []),
    new Cell(new Posn(13, 13), []),
    new Cell(new Posn(14, 13), []),
    new Cell(new Posn(15, 13), []),
    new Cell(new Posn(16, 13), ["right"]),
    new Cell(new Posn(17, 13), ["left"]),
    new Cell(new Posn(18, 13), ["up", "down"]),
    new Cell(new Posn(19, 13), ["up", "down"]),
    new Cell(new Posn(20, 13), []),
    new Cell(new Posn(21, 13), ["up", "down"]),
    new Cell(new Posn(22, 13), ["up", "down"]),
    new Cell(new Posn(23, 13), ["up", "down"]),
    new Cell(new Posn(24, 13), ["up", "down"]),
    new Cell(new Posn(25, 13), ["up", "down"]),
    new Cell(new Posn(0, 14), ["up", "left"]),
    new Cell(new Posn(1, 14), ["up"]),
    new Cell(new Posn(2, 14), ["up"]),
    new Cell(new Posn(3, 14), ["up"]),
    new Cell(new Posn(4, 14), ["up", "right"]),
    new Cell(new Posn(5, 14), ["left", "right"]),
    new Cell(new Posn(6, 14), ["up", "left"]),
    new Cell(new Posn(7, 14), ["up", "right"]),
    new Cell(new Posn(8, 14), ["left", "right"]),
    new Cell(new Posn(9, 14), ["left"]),
    new Cell(new Posn(10, 14), []),
    new Cell(new Posn(11, 14), []),
    new Cell(new Posn(12, 14), []),
    new Cell(new Posn(13, 14), []),
    new Cell(new Posn(14, 14), []),
    new Cell(new Posn(15, 14), []),
    new Cell(new Posn(16, 14), ["right"]),
    new Cell(new Posn(17, 14), ["left", "right"]),
    new Cell(new Posn(18, 14), ["up", "left"]),
    new Cell(new Posn(19, 14), ["up", "right"]),
    new Cell(new Posn(20, 14), ["left", "right"]),
    new Cell(new Posn(21, 14), ["up", "left"]),
    new Cell(new Posn(22, 14), ["up"]),
    new Cell(new Posn(23, 14), ["up"]),
    new Cell(new Posn(24, 14), ["up"]),
    new Cell(new Posn(25, 14), ["up", "right"]),
    new Cell(new Posn(0, 15), ["left"]),
    new Cell(new Posn(1, 15), []),
    new Cell(new Posn(2, 15), []),
    new Cell(new Posn(3, 15), []),
    new Cell(new Posn(4, 15), ["right"]),
    new Cell(new Posn(5, 15), ["left", "right"]),
    new Cell(new Posn(6, 15), ["left"]),
    new Cell(new Posn(7, 15), ["right"]),
    new Cell(new Posn(8, 15), ["left", "right"]),
    new Cell(new Posn(9, 15), ["left", "down"]),
    new Cell(new Posn(10, 15), ["down"]),
    new Cell(new Posn(11, 15), ["down"]),
    new Cell(new Posn(12, 15), ["down"]),
    new Cell(new Posn(13, 15), ["down"]),
    new Cell(new Posn(14, 15), ["down"]),
    new Cell(new Posn(15, 15), ["down"]),
    new Cell(new Posn(16, 15), ["right", "down"]),
    new Cell(new Posn(17, 15), ["left", "right"]),
    new Cell(new Posn(18, 15), ["left"]),
    new Cell(new Posn(19, 15), ["right"]),
    new Cell(new Posn(20, 15), ["left", "right"]),
    new Cell(new Posn(21, 15), ["left"]),
    new Cell(new Posn(22, 15), []),
    new Cell(new Posn(23, 15), []),
    new Cell(new Posn(24, 15), []),
    new Cell(new Posn(25, 15), ["right"]),
    new Cell(new Posn(0, 16), ["left"]),
    new Cell(new Posn(1, 16), []),
    new Cell(new Posn(2, 16), []),
    new Cell(new Posn(3, 16), []),
    new Cell(new Posn(4, 16), ["right"]),
    new Cell(new Posn(5, 16), ["left", "right"]),
    new Cell(new Posn(6, 16), ["left"]),
    new Cell(new Posn(7, 16), ["right"]),
    new Cell(new Posn(8, 16), ["left"]),
    new Cell(new Posn(9, 16), ["up", "down"]),
    new Cell(new Posn(10, 16), ["up", "down"]),
    new Cell(new Posn(11, 16), ["up", "down"]),
    new Cell(new Posn(12, 16), ["up", "down"]),
    new Cell(new Posn(13, 16), ["up", "down"]),
    new Cell(new Posn(14, 16), ["up", "down"]),
    new Cell(new Posn(15, 16), ["up", "down"]),
    new Cell(new Posn(16, 16), ["up", "down"]),
    new Cell(new Posn(17, 16), ["right"]),
    new Cell(new Posn(18, 16), ["left"]),
    new Cell(new Posn(19, 16), ["right"]),
    new Cell(new Posn(20, 16), ["left", "right"]),
    new Cell(new Posn(21, 16), ["left"]),
    new Cell(new Posn(22, 16), []),
    new Cell(new Posn(23, 16), []),
    new Cell(new Posn(24, 16), []),
    new Cell(new Posn(25, 16), ["right"]),
    new Cell(new Posn(0, 17), ["left"]),
    new Cell(new Posn(1, 17), []),
    new Cell(new Posn(2, 17), []),
    new Cell(new Posn(3, 17), []),
    new Cell(new Posn(4, 17), ["right"]),
    new Cell(new Posn(5, 17), ["left", "right"]),
    new Cell(new Posn(6, 17), ["left"]),
    new Cell(new Posn(7, 17), ["right"]),
    new Cell(new Posn(8, 17), ["left", "right"]),
    new Cell(new Posn(9, 17), ["up", "left"]),
    new Cell(new Posn(10, 17), ["up"]),
    new Cell(new Posn(11, 17), ["up"]),
    new Cell(new Posn(12, 17), ["up"]),
    new Cell(new Posn(13, 17), ["up"]),
    new Cell(new Posn(14, 17), ["up"]),
    new Cell(new Posn(15, 17), ["up"]),
    new Cell(new Posn(16, 17), ["up", "right"]),
    new Cell(new Posn(17, 17), ["left", "right"]),
    new Cell(new Posn(18, 17), ["left"]),
    new Cell(new Posn(19, 17), ["right"]),
    new Cell(new Posn(20, 17), ["left", "right"]),
    new Cell(new Posn(21, 17), ["left"]),
    new Cell(new Posn(22, 17), []),
    new Cell(new Posn(23, 17), []),
    new Cell(new Posn(24, 17), []),
    new Cell(new Posn(25, 17), ["right"]),
    new Cell(new Posn(0, 18), ["left", "down"]),
    new Cell(new Posn(1, 18), ["down"]),
    new Cell(new Posn(2, 18), ["down"]),
    new Cell(new Posn(3, 18), ["down"]),
    new Cell(new Posn(4, 18), ["right", "down"]),
    new Cell(new Posn(5, 18), ["left", "right"]),
    new Cell(new Posn(6, 18), ["left", "down"]),
    new Cell(new Posn(7, 18), ["right", "down"]),
    new Cell(new Posn(8, 18), ["left", "right"]),
    new Cell(new Posn(9, 18), ["left", "down"]),
    new Cell(new Posn(10, 18), ["down"]),
    new Cell(new Posn(11, 18), ["down"]),
    new Cell(new Posn(12, 18), []),
    new Cell(new Posn(13, 18), []),
    new Cell(new Posn(14, 18), ["down"]),
    new Cell(new Posn(15, 18), ["down"]),
    new Cell(new Posn(16, 18), ["right", "down"]),
    new Cell(new Posn(17, 18), ["left", "right"]),
    new Cell(new Posn(18, 18), ["left", "down"]),
    new Cell(new Posn(19, 18), ["right", "down"]),
    new Cell(new Posn(20, 18), ["left", "right"]),
    new Cell(new Posn(21, 18), ["left", "down"]),
    new Cell(new Posn(22, 18), ["down"]),
    new Cell(new Posn(23, 18), ["down"]),
    new Cell(new Posn(24, 18), ["down"]),
    new Cell(new Posn(25, 18), ["right", "down"]),
    new Cell(new Posn(0, 19), ["up", "left"]),
    new Cell(new Posn(1, 19), ["up", "down"]),
    new Cell(new Posn(2, 19), ["up", "down"]),
    new Cell(new Posn(3, 19), ["up", "down"]),
    new Cell(new Posn(4, 19), ["up", "down"]),
    new Cell(new Posn(5, 19), []),
    new Cell(new Posn(6, 19), ["up", "down"]),
    new Cell(new Posn(7, 19), ["up", "down"]),
    new Cell(new Posn(8, 19), ["down"]),
    new Cell(new Posn(9, 19), ["up", "down"]),
    new Cell(new Posn(10, 19), ["up", "down"]),
    new Cell(new Posn(11, 19), ["up", "right"]),
    new Cell(new Posn(12, 19), ["left"]),
    new Cell(new Posn(13, 19), ["right"]),
    new Cell(new Posn(14, 19), ["up", "left"]),
    new Cell(new Posn(15, 19), ["up", "down"]),
    new Cell(new Posn(16, 19), ["up", "down"]),
    new Cell(new Posn(17, 19), ["down"]),
    new Cell(new Posn(18, 19), ["up", "down"]),
    new Cell(new Posn(19, 19), ["up", "down"]),
    new Cell(new Posn(20, 19), []),
    new Cell(new Posn(21, 19), ["up", "down"]),
    new Cell(new Posn(22, 19), ["up", "down"]),
    new Cell(new Posn(23, 19), ["up", "down"]),
    new Cell(new Posn(24, 19), ["up", "down"]),
    new Cell(new Posn(25, 19), ["up", "right"]),
    new Cell(new Posn(0, 20), ["left", "right"]),
    new Cell(new Posn(1, 20), ["up", "left"]),
    new Cell(new Posn(2, 20), ["up"]),
    new Cell(new Posn(3, 20), ["up"]),
    new Cell(new Posn(4, 20), ["up", "right"]),
    new Cell(new Posn(5, 20), ["left", "right"]),
    new Cell(new Posn(6, 20), ["up", "left"]),
    new Cell(new Posn(7, 20), ["up"]),
    new Cell(new Posn(8, 20), ["up"]),
    new Cell(new Posn(9, 20), ["up"]),
    new Cell(new Posn(10, 20), ["up", "right"]),
    new Cell(new Posn(11, 20), ["left", "right"]),
    new Cell(new Posn(12, 20), ["left"]),
    new Cell(new Posn(13, 20), ["right"]),
    new Cell(new Posn(14, 20), ["left", "right"]),
    new Cell(new Posn(15, 20), ["up", "left"]),
    new Cell(new Posn(16, 20), ["up"]),
    new Cell(new Posn(17, 20), ["up"]),
    new Cell(new Posn(18, 20), ["up"]),
    new Cell(new Posn(19, 20), ["up", "right"]),
    new Cell(new Posn(20, 20), ["left", "right"]),
    new Cell(new Posn(21, 20), ["up", "left"]),
    new Cell(new Posn(22, 20), ["up"]),
    new Cell(new Posn(23, 20), ["up"]),
    new Cell(new Posn(24, 20), ["up", "right"]),
    new Cell(new Posn(25, 20), ["left", "right"]),
    new Cell(new Posn(0, 21), ["left", "right"]),
    new Cell(new Posn(1, 21), ["left", "down"]),
    new Cell(new Posn(2, 21), ["down"]),
    new Cell(new Posn(3, 21), []),
    new Cell(new Posn(4, 21), ["right"]),
    new Cell(new Posn(5, 21), ["left", "right"]),
    new Cell(new Posn(6, 21), ["left", "down"]),
    new Cell(new Posn(7, 21), ["down"]),
    new Cell(new Posn(8, 21), ["down"]),
    new Cell(new Posn(9, 21), ["down"]),
    new Cell(new Posn(10, 21), ["right", "down"]),
    new Cell(new Posn(11, 21), ["left", "right"]),
    new Cell(new Posn(12, 21), ["left", "down"]),
    new Cell(new Posn(13, 21), ["right", "down"]),
    new Cell(new Posn(14, 21), ["left", "right"]),
    new Cell(new Posn(15, 21), ["left", "down"]),
    new Cell(new Posn(16, 21), ["down"]),
    new Cell(new Posn(17, 21), ["down"]),
    new Cell(new Posn(18, 21), ["down"]),
    new Cell(new Posn(19, 21), ["right", "down"]),
    new Cell(new Posn(20, 21), ["left", "right"]),
    new Cell(new Posn(21, 21), ["left"]),
    new Cell(new Posn(22, 21), []),
    new Cell(new Posn(23, 21), ["down"]),
    new Cell(new Posn(24, 21), ["right", "down"]),
    new Cell(new Posn(25, 21), ["left", "right"]),
    new Cell(new Posn(0, 22), ["left", "down"]),
    new Cell(new Posn(1, 22), ["up", "down"]),
    new Cell(new Posn(2, 22), ["up", "right"]),
    new Cell(new Posn(3, 22), ["left"]),
    new Cell(new Posn(4, 22), ["right"]),
    new Cell(new Posn(5, 22), ["left"]),
    new Cell(new Posn(6, 22), ["up", "down"]),
    new Cell(new Posn(7, 22), ["up", "down"]),
    new Cell(new Posn(8, 22), ["up"]),
    new Cell(new Posn(9, 22), ["up", "down"]),
    new Cell(new Posn(10, 22), ["up", "down"]),
    new Cell(new Posn(11, 22), ["down"]),
    new Cell(new Posn(12, 22), ["up", "down"]),
    new Cell(new Posn(13, 22), ["up", "down"]),
    new Cell(new Posn(14, 22), ["down"]),
    new Cell(new Posn(15, 22), ["up", "down"]),
    new Cell(new Posn(16, 22), ["up", "down"]),
    new Cell(new Posn(17, 22), ["up"]),
    new Cell(new Posn(18, 22), ["up", "down"]),
    new Cell(new Posn(19, 22), ["up", "down"]),
    new Cell(new Posn(20, 22), ["right"]),
    new Cell(new Posn(21, 22), ["left"]),
    new Cell(new Posn(22, 22), ["right"]),
    new Cell(new Posn(23, 22), ["up", "left"]),
    new Cell(new Posn(24, 22), ["up", "down"]),
    new Cell(new Posn(25, 22), ["right", "down"]),
    new Cell(new Posn(0, 23), ["up", "left"]),
    new Cell(new Posn(1, 23), ["up", "right"]),
    new Cell(new Posn(2, 23), ["left", "right"]),
    new Cell(new Posn(3, 23), ["left"]),
    new Cell(new Posn(4, 23), ["right"]),
    new Cell(new Posn(5, 23), ["left", "right"]),
    new Cell(new Posn(6, 23), ["up", "left"]),
    new Cell(new Posn(7, 23), ["up", "right"]),
    new Cell(new Posn(8, 23), ["left", "right"]),
    new Cell(new Posn(9, 23), ["up", "left"]),
    new Cell(new Posn(10, 23), ["up"]),
    new Cell(new Posn(11, 23), ["up"]),
    new Cell(new Posn(12, 23), ["up"]),
    new Cell(new Posn(13, 23), ["up"]),
    new Cell(new Posn(14, 23), ["up"]),
    new Cell(new Posn(15, 23), ["up"]),
    new Cell(new Posn(16, 23), ["up", "right"]),
    new Cell(new Posn(17, 23), ["left", "right"]),
    new Cell(new Posn(18, 23), ["up", "left"]),
    new Cell(new Posn(19, 23), ["up", "right"]),
    new Cell(new Posn(20, 23), ["left", "right"]),
    new Cell(new Posn(21, 23), ["left"]),
    new Cell(new Posn(22, 23), ["right"]),
    new Cell(new Posn(23, 23), ["left", "right"]),
    new Cell(new Posn(24, 23), ["up", "left"]),
    new Cell(new Posn(25, 23), ["up", "right"]),
    new Cell(new Posn(0, 24), ["left", "down"]),
    new Cell(new Posn(1, 24), ["right", "down"]),
    new Cell(new Posn(2, 24), ["left", "right"]),
    new Cell(new Posn(3, 24), ["left", "down"]),
    new Cell(new Posn(4, 24), ["right", "down"]),
    new Cell(new Posn(5, 24), ["left", "right"]),
    new Cell(new Posn(6, 24), ["left"]),
    new Cell(new Posn(7, 24), ["right"]),
    new Cell(new Posn(8, 24), ["left", "right"]),
    new Cell(new Posn(9, 24), ["left", "down"]),
    new Cell(new Posn(10, 24), ["down"]),
    new Cell(new Posn(11, 24), ["down"]),
    new Cell(new Posn(12, 24), []),
    new Cell(new Posn(13, 24), []),
    new Cell(new Posn(14, 24), ["down"]),
    new Cell(new Posn(15, 24), ["down"]),
    new Cell(new Posn(16, 24), ["right", "down"]),
    new Cell(new Posn(17, 24), ["left", "right"]),
    new Cell(new Posn(18, 24), ["left"]),
    new Cell(new Posn(19, 24), ["right"]),
    new Cell(new Posn(20, 24), ["left", "right"]),
    new Cell(new Posn(21, 24), ["left", "down"]),
    new Cell(new Posn(22, 24), ["right", "down"]),
    new Cell(new Posn(23, 24), ["left", "right"]),
    new Cell(new Posn(24, 24), ["left", "down"]),
    new Cell(new Posn(25, 24), ["right", "down"]),
    new Cell(new Posn(0, 25), ["up", "left"]),
    new Cell(new Posn(1, 25), ["up", "down"]),
    new Cell(new Posn(2, 25), ["down"]),
    new Cell(new Posn(3, 25), ["up", "down"]),
    new Cell(new Posn(4, 25), ["up", "down"]),
    new Cell(new Posn(5, 25), ["right", "down"]),
    new Cell(new Posn(6, 25), ["left"]),
    new Cell(new Posn(7, 25), ["right"]),
    new Cell(new Posn(8, 25), ["left", "down"]),
    new Cell(new Posn(9, 25), ["up", "down"]),
    new Cell(new Posn(10, 25), ["up", "down"]),
    new Cell(new Posn(11, 25), ["up", "right"]),
    new Cell(new Posn(12, 25), ["left"]),
    new Cell(new Posn(13, 25), ["right"]),
    new Cell(new Posn(14, 25), ["up", "left"]),
    new Cell(new Posn(15, 25), ["up", "down"]),
    new Cell(new Posn(16, 25), ["up", "down"]),
    new Cell(new Posn(17, 25), ["right", "down"]),
    new Cell(new Posn(18, 25), ["left"]),
    new Cell(new Posn(19, 25), ["right"]),
    new Cell(new Posn(20, 25), ["left", "down"]),
    new Cell(new Posn(21, 25), ["up", "down"]),
    new Cell(new Posn(22, 25), ["up", "down"]),
    new Cell(new Posn(23, 25), ["down"]),
    new Cell(new Posn(24, 25), ["up", "down"]),
    new Cell(new Posn(25, 25), ["up", "right"]),
    new Cell(new Posn(0, 26), ["left", "right"]),
    new Cell(new Posn(1, 26), ["up", "left"]),
    new Cell(new Posn(2, 26), ["up"]),
    new Cell(new Posn(3, 26), ["up"]),
    new Cell(new Posn(4, 26), ["up"]),
    new Cell(new Posn(5, 26), ["up"]),
    new Cell(new Posn(6, 26), []),
    new Cell(new Posn(7, 26), []),
    new Cell(new Posn(8, 26), ["up"]),
    new Cell(new Posn(9, 26), ["up"]),
    new Cell(new Posn(10, 26), ["up", "right"]),
    new Cell(new Posn(11, 26), ["left", "right"]),
    new Cell(new Posn(12, 26), ["left"]),
    new Cell(new Posn(13, 26), ["right"]),
    new Cell(new Posn(14, 26), ["left", "right"]),
    new Cell(new Posn(15, 26), ["up", "left"]),
    new Cell(new Posn(16, 26), ["up"]),
    new Cell(new Posn(17, 26), ["up"]),
    new Cell(new Posn(18, 26), []),
    new Cell(new Posn(19, 26), []),
    new Cell(new Posn(20, 26), ["up"]),
    new Cell(new Posn(21, 26), ["up"]),
    new Cell(new Posn(22, 26), ["up"]),
    new Cell(new Posn(23, 26), ["up"]),
    new Cell(new Posn(24, 26), ["up", "right"]),
    new Cell(new Posn(25, 26), ["left", "right"]),
    new Cell(new Posn(0, 27), ["left", "right"]),
    new Cell(new Posn(1, 27), ["left", "down"]),
    new Cell(new Posn(2, 27), ["down"]),
    new Cell(new Posn(3, 27), ["down"]),
    new Cell(new Posn(4, 27), ["down"]),
    new Cell(new Posn(5, 27), ["down"]),
    new Cell(new Posn(6, 27), ["down"]),
    new Cell(new Posn(7, 27), ["down"]),
    new Cell(new Posn(8, 27), ["down"]),
    new Cell(new Posn(9, 27), ["down"]),
    new Cell(new Posn(10, 27), ["right", "down"]),
    new Cell(new Posn(11, 27), ["left", "right"]),
    new Cell(new Posn(12, 27), ["left", "down"]),
    new Cell(new Posn(13, 27), ["right", "down"]),
    new Cell(new Posn(14, 27), ["left", "right"]),
    new Cell(new Posn(15, 27), ["left", "down"]),
    new Cell(new Posn(16, 27), ["down"]),
    new Cell(new Posn(17, 27), ["down"]),
    new Cell(new Posn(18, 27), ["down"]),
    new Cell(new Posn(19, 27), ["down"]),
    new Cell(new Posn(20, 27), ["down"]),
    new Cell(new Posn(21, 27), ["down"]),
    new Cell(new Posn(22, 27), ["down"]),
    new Cell(new Posn(23, 27), ["down"]),
    new Cell(new Posn(24, 27), ["right", "down"]),
    new Cell(new Posn(25, 27), ["left", "right"]),
    new Cell(new Posn(0, 28), ["left", "down"]),
    new Cell(new Posn(1, 28), ["up", "down"]),
    new Cell(new Posn(2, 28), ["up", "down"]),
    new Cell(new Posn(3, 28), ["up", "down"]),
    new Cell(new Posn(4, 28), ["up", "down"]),
    new Cell(new Posn(5, 28), ["up", "down"]),
    new Cell(new Posn(6, 28), ["up", "down"]),
    new Cell(new Posn(7, 28), ["up", "down"]),
    new Cell(new Posn(8, 28), ["up", "down"]),
    new Cell(new Posn(9, 28), ["up", "down"]),
    new Cell(new Posn(10, 28), ["up", "down"]),
    new Cell(new Posn(11, 28), ["down"]),
    new Cell(new Posn(12, 28), ["up", "down"]),
    new Cell(new Posn(13, 28), ["up", "down"]),
    new Cell(new Posn(14, 28), ["down"]),
    new Cell(new Posn(15, 28), ["up", "down"]),
    new Cell(new Posn(16, 28), ["up", "down"]),
    new Cell(new Posn(17, 28), ["up", "down"]),
    new Cell(new Posn(18, 28), ["up", "down"]),
    new Cell(new Posn(19, 28), ["up", "down"]),
    new Cell(new Posn(20, 28), ["up", "down"]),
    new Cell(new Posn(21, 28), ["up", "down"]),
    new Cell(new Posn(22, 28), ["up", "down"]),
    new Cell(new Posn(23, 28), ["up", "down"]),
    new Cell(new Posn(24, 28), ["up", "down"]),
    new Cell(new Posn(25, 28), ["right", "down"])
    ];
}